# -*- coding: utf-8 -*-
"""Banking System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCZsBLH2j7Cl-ckeiRaFj--N8OYB4hH4
"""

def banking_system():
    balance = 0
    recipient_balance = 0

    while True:
        print("\nBanking System Menu:")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Transfer Money")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            print(f"Your current balance is: {balance}")
        elif choice == '2':
            try:
                amount = float(input("Enter the amount to deposit: "))
                if amount > 0:
                    balance += amount
                    print(f"Deposit successful. New balance: {balance}")
                else:
                    print("Invalid deposit amount.")
            except ValueError:
                print("Invalid input. Please enter a numeric value.")
        elif choice == '3':
            try:
                amount = float(input("Enter the amount to withdraw: "))
                if amount > 0 and amount <= balance:
                    balance -= amount
                    print(f"Withdrawal successful. New balance: {balance}")
                elif amount <= 0:
                    print("Invalid withdrawal amount.")
                else:
                    print("Insufficient funds.")
            except ValueError:
                print("Invalid input. Please enter a numeric value.")
        elif choice == '4':
            try:
                recipient = input("Enter recipient's account number: ")
                amount = float(input("Enter the amount to transfer: "))
                if amount > 0 and amount <= balance:
                    balance -= amount
                    recipient_balance += amount  # Update recipient's balance
                    print(f"Transfer successful. New balance: {balance}")
                    print(f"Recipient's new balance: {recipient_balance}")
                elif amount <= 0:
                    print("Invalid transfer amount.")
                else:
                    print("Insufficient funds.")
            except ValueError:
                print("Invalid input. Please enter a numeric value.")
        elif choice == '5':
            print("Thank you for using our banking system. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    banking_system()